#define __unsigned_chars__ 1	/* Predefined */
#define __PRAGMA_REDEFINE_EXTNAME 1	/* Predefined */
#define __DATE__ "Oct 26 2019"	/* Predefined */
#define __TIME__ "23:11:54"	/* Predefined */
#define __STDC__ 1	/* Predefined */
#define __STDC_HOSTED__ 1	/* Predefined */
#define __cplusplus 201402L	/* Predefined */
#define _WCHAR_T 1	/* Predefined */
#define __CHAR16_T_AND_CHAR32_T 1	/* Predefined */
#define _BOOL 1	/* Predefined */
#define __ARRAY_OPERATORS 1	/* Predefined */
#define __PLACEMENT_DELETE 1	/* Predefined */
#define __EDG_RUNTIME_USES_NAMESPACES 1	/* Predefined */
#define __EDG_IA64_ABI 1	/* Predefined */
#define __EDG_IA64_ABI_VARIANT_CTORS_AND_DTORS_RETURN_THIS 1	/* Predefined */
#define __EDG_IA64_ABI_USE_VARIANT_INT_STATIC_INIT_GUARD 1	/* Predefined */
#define __cpp_initializer_lists 200806	/* Predefined */
#define __cpp_sized_deallocation 201309	/* Predefined */
#define __cpp_unicode_characters 200704	/* Predefined */
#define __cpp_aggregate_nsdmi 201304	/* Predefined */
#define __cpp_alias_templates 200704	/* Predefined */
#define __cpp_attributes 200809	/* Predefined */
#define __cpp_binary_literals 201304	/* Predefined */
#define __cpp_decltype 200707	/* Predefined */
#define __cpp_decltype_auto 201304	/* Predefined */
#define __cpp_delegating_constructors 200604	/* Predefined */
#define __cpp_generic_lambdas 201304	/* Predefined */
#define __cpp_inheriting_constructors 200802	/* Predefined */
#define __cpp_init_captures 201304	/* Predefined */
#define __cpp_lambdas 200907	/* Predefined */
#define __cpp_nsdmi 200809	/* Predefined */
#define __cpp_raw_strings 200710	/* Predefined */
#define __cpp_ref_qualifiers 200710	/* Predefined */
#define __cpp_return_type_deduction 201304	/* Predefined */
#define __cpp_rvalue_references 200610	/* Predefined */
#define __cpp_unicode_literals 200710	/* Predefined */
#define __cpp_user_defined_literals 200809	/* Predefined */
#define __cpp_variable_templates 201304	/* Predefined */
#define __cpp_variadic_templates 200704	/* Predefined */
#define __cpp_constexpr 201304	/* Predefined */
#define __cpp_range_based_for 200907	/* Predefined */
#define __cpp_static_assert 200410	/* Predefined */
#define __TI_C99_COMPLEX_ENABLED__ 1	/* Predefined */
#define __EDG_TYPE_TRAITS_ENABLED 1	/* Predefined */
#define __VARIADIC_TEMPLATES 1	/* Predefined */
#define __EDG_CONSTEXPR_ENABLED__ 1	/* Predefined */
#define __edg_front_end__ 1	/* Predefined */
#define __EDG_VERSION__ 413	/* Predefined */
#define __EDG_SIZE_TYPE__ unsigned int	/* Predefined */
#define __EDG_PTRDIFF_TYPE__ int	/* Predefined */
#define __GNUC_STDC_INLINE__ 1	/* Predefined */
#define __VERSION__ "EDG g++ 4.8 mode"	/* Predefined */
#define __CHAR16_TYPE__ unsigned short	/* Predefined */
#define __CHAR32_TYPE__ unsigned long	/* Predefined */
#define __TI_COMPILER_VERSION__ 19006000	/* Predefined */
#define __COMPILER_VERSION__ 19006000	/* Predefined */
#define __TI_COMPILER_VERSION_QUAL_ID__ 19173	/* Predefined */
#define __TI_COMPILER_VERSION_QUAL__ QUAL_LETTER	/* Predefined */
#define __MSP430__ 1	/* Predefined */
#define __SIZE_T_TYPE__ unsigned	/* Predefined */
#define __PTRDIFF_T_TYPE__ int	/* Predefined */
#define __WCHAR_T_TYPE__ unsigned int	/* Predefined */
#define __TI_EABI__ 1	/* Predefined */
#define __ELF__ 1	/* Predefined */
#define __little_endian__ 1	/* Predefined */
#define __LITTLE_ENDIAN__ 1	/* Predefined */
#define __TI_STRICT_ANSI_MODE__ 0	/* Predefined */
#define __TI_WCHAR_T_BITS__ 16	/* Predefined */
#define __TI_GNU_ATTRIBUTE_SUPPORT__ 1	/* Predefined */
#define __TI_STRICT_FP_MODE__ 1	/* Predefined */
#define __CHAR_BIT__ 8	/* Predefined */
#define __SCHAR_MAX__ 127	/* Predefined */
#define __SHRT_MAX__ 32767	/* Predefined */
#define __INT_MAX__ 32767	/* Predefined */
#define __LONG_MAX__ 2147483647	/* Predefined */
#define __LONG_LONG_MAX__ 9223372036854775807	/* Predefined */
#define __SIZEOF_INT__ 2	/* Predefined */
#define __SIZEOF_SHORT__ 2	/* Predefined */
#define __SIZEOF_LONG__ 4	/* Predefined */
#define __SIZEOF_LONG_LONG__ 8	/* Predefined */
#define __SIZEOF_WCHAR_T__ 2	/* Predefined */
#define __SIZEOF_FLOAT__ 4	/* Predefined */
#define __SIZEOF_DOUBLE__ 8	/* Predefined */
#define __SIZEOF_LONG_DOUBLE__ 8	/* Predefined */
#define __SIZEOF_SIZE_T__ 2	/* Predefined */
#define __SIZEOF_WINT_T__ 2	/* Predefined */
#define __SIZEOF_PTRDIFF_T__ 2	/* Predefined */
#define _OPTIMIZE_FOR_SPACE 1
#define _INLINE 1
