#define __cplusplus 199711L
#define __cpp_exceptions 199711
#define __cpp_rtti 199711
#define __cpp_attributes 200809
#define __has_cpp_attribute(x) __oracle_has_attribute(x)
#define __STDC__ 1
#define _WCHAR_T 
#define _BOOL 1
#define __ARRAYNEW 1
#define _TEMPLATE_NO_EXTDEF 1
#define __DATE__ "Apr 12 2018"
#define __TIME__ "08:40:12"
#define __LINE__ 
#define __FILE__ 
#define _SIGNEDCHAR_ 1
#define __PRAGMA_REDEFINE_EXTNAME 1
#define __asm asm
#define __asm__ asm
#define __volatile volatile
#define __volatile__ volatile
#define __signed__ signed
#define __SIZE_TYPE__ unsigned long
#define __PTRDIFF_TYPE__ long
#define __WCHAR_TYPE__ int
#define __gnuc_va_list va_list
#define _GNU_SOURCE 1
#define __builtin_huge_val __oracle_builtin_huge_val
#define __builtin_huge_valf __oracle_builtin_huge_valf
#define __builtin_huge_vall __oracle_builtin_huge_vall
#define __builtin_infinity __oracle_builtin_infinity
#define __builtin_isfinite __oracle_builtin_isfinite
#define __builtin_isinf __oracle_builtin_isinf
#define __builtin_isnan __oracle_builtin_isnan
#define __builtin_isnormal __oracle_builtin_isnormal
#define __builtin_signbit __oracle_builtin_signbit
#define __builtin_isgreater __oracle_builtin_isgreater
#define __builtin_isgreaterequal __oracle_builtin_isgreaterequal
#define __builtin_isless __oracle_builtin_isless
#define __builtin_islessequal __oracle_builtin_islessequal
#define __builtin_islessgreater __oracle_builtin_islessgreater
#define __builtin_isunordered __oracle_builtin_isunordered
#define __builtin_constant_p __oracle_builtin_constant_p
#define __attribute __attribute__
#define __is_pod(x) __oracle_is_pod(x)
#define __is_empty(x) __oracle_is_empty(x)
#define __is_final(x) __oracle_is_final(x)
#define __is_enum(x) __oracle_is_enum(x)
#define __is_class(x) __oracle_is_class(x)
#define __is_union(x) __oracle_is_union(x)
#define __is_abstract(x) __oracle_is_abstract(x)
#define __is_polymorphic(x) __oracle_is_polymorphic(x)
#define __has_virtual_destructor(x) __oracle_has_virtual_destructor(x)
#define __has_trivial_constructor(x) __oracle_has_trivial_constructor(x)
#define __has_trivial_destructor(x) __oracle_has_trivial_destructor(x)
#define __is_base_of(x,y) __oracle_is_base_of(x,y)
#define __is_trivial(x) __oracle_is_trivial(x)
#define __is_standard_layout(x) __oracle_is_standard_layout(x)
#define __is_literal_type(x) __oracle_is_literal_type(x)
#define __has_trivial_copy(x) __oracle_has_trivial_copy(x)
#define __has_trivial_move_constructor(x) __oracle_has_trivial_move_constructor(x)
#define __has_trivial_assign(x) __oracle_has_trivial_assign(x)
#define __has_trivial_move_assign(x) __oracle_has_trivial_move_assign(x)
#define __has_nothrow_constructor(x) __oracle_has_nothrow_constructor(x)
#define __has_nothrow_copy(x) __oracle_has_nothrow_copy(x)
#define __has_nothrow_assign(x) __oracle_has_nothrow_assign(x)
#define __underlying_type(x) __oracle_underlying_type(x)
#define __has_attribute(x) __oracle_has_attribute(x)
#define __restrict__ __restrict
#define __extension__ 
#define __null 0
#define __alignof__ __alignof
#define __SUNPRO_CC 0x5150
#define __MATHERR_RENAME_EXCEPTION 1
#define __unix 1
#define __unix__ 1
#define __linux 1
#define __linux__ 1
#define __gnu__linux__ 1
#define __x86_64 1
#define __x86_64__ 1
#define __amd64 1
#define __amd64__ 1
#define _LP64 1
#define __LP64__ 1
#define __ORDER_LITTLE_ENDIAN__ 1234
#define __ORDER_BIG_ENDIAN__ 4321
#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __BUILTIN_VA_STRUCT 1
#define linux 1
#define unix 1
#define __SUN_PREFETCH 1
#define __SUNPRO_CC_COMPAT 'G'
#define _SUN_BUILTINS
#define __STDC_HOSTED__ 1
#define __GXX_WEAK__ 1
#define __DEPRECATED 1
#define __EXCEPTIONS 1
#define __GXX_ABI_VERSION 1002
#define _GLIBCXX__PTHREADS 1
#define __GCC_ATOMIC_BOOL_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR16_T_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR32_T_LOCK_FREE 2
#define __GCC_ATOMIC_WCHAR_T_LOCK_FREE 2
#define __GCC_ATOMIC_SHORT_LOCK_FREE 2
#define __GCC_ATOMIC_INT_LOCK_FREE 2
#define __GCC_ATOMIC_LONG_LOCK_FREE 2
#define __GCC_ATOMIC_LLONG_LOCK_FREE 2
#define __GCC_ATOMIC_POINTER_LOCK_FREE 2
#define __GCC_ATOMIC_TEST_AND_SET_TRUEVAL 1
#define __ATOMIC_RELAXED 0
#define __ATOMIC_CONSUME 1
#define __ATOMIC_ACQUIRE 2
#define __ATOMIC_RELEASE 3
#define __ATOMIC_ACQ_REL 4
#define __ATOMIC_SEQ_CST 5
#define __WINT_TYPE__ unsigned int
#define __SCHAR_MAX__ 127
#define __SHRT_MAX__ 32767
#define __INT_MAX__ 2147483647
#define __LONG_LONG_MAX__ 9223372036854775807LL
#define __WCHAR_MAX__ 2147483647
#define __INTMAX_MAX__ 9223372036854775807LL
#define __CHAR_BIT__ 8
#define __FLT_RADIX__ 2
#define __FLT_MANT_DIG__ 24
#define __FLT_DIG__ 6
#define __FLT_MIN_EXP__ (-125)
#define __FLT_MIN_10_EXP__ (-37)
#define __FLT_MAX_EXP__ 128
#define __FLT_MAX_10_EXP__ 38
#define __FLT_MAX__ 3.40282347e+38F
#define __FLT_MIN__ 1.17549435e-38F
#define __FLT_EPSILON__ 1.19209290e-7F
#define __FLT_DENORM_MIN__ 1.40129846e-45F
#define __FLT_HAS_DENORM__ 1
#define __FLT_HAS_INFINITY__ 1
#define __FLT_HAS_QUIET_NAN__ 1
#define __DBL_MANT_DIG__ 53
#define __DBL_DIG__ 15
#define __DBL_MIN_EXP__ (-1021)
#define __DBL_MIN_10_EXP__ (-307)
#define __DBL_MAX_EXP__ 1024
#define __DBL_MAX_10_EXP__ 308
#define __DBL_MAX__ 1.7976931348623157e+308
#define __DBL_MIN__ 2.2250738585072014e-308
#define __DBL_EPSILON__ 2.2204460492503131e-16
#define __DBL_DENORM_MIN__ 4.9406564584124654e-324
#define __DBL_HAS_DENORM__ 1
#define __DBL_HAS_INFINITY__ 1
#define __DBL_HAS_QUIET_NAN__ 1
#define __LDBL_MANT_DIG__ 64
#define __LDBL_EPSILON__ 1.08420217248550443401e-19L
#define __LDBL_DIG__ 18
#define __LDBL_MIN_EXP__ (-16381)
#define __LDBL_MIN__ 3.36210314311209350626e-4932L
#define __LDBL_MIN_10_EXP__ (-4931)
#define __LDBL_MAX_EXP__ 16384
#define __LDBL_MAX__ 1.18973149535723176502e+4932L
#define __LDBL_MAX_10_EXP__ 4932
#define __DECIMAL_DIG__ 21
#define __LDBL_DENORM_MIN__ 3.64519953188247460253e-4951L
#define __LDBL_HAS_DENORM__ 1
#define __LDBL_HAS_INFINITY__ 1
#define __LDBL_HAS_QUIET_NAN__ 1
#define __REGISTER_PREFIX__
#define __USER_LABEL_PREFIX__
#define __NO_INLINE__ 1
#define __FINITE_MATH_ONLY__ 0
#define __ELF__ 1
#define __INTMAX_TYPE__ long int
#define __UINTMAX_TYPE__ long unsigned int
#define __LONG_MAX__ 9223372036854775807L
#define __FLT_EVAL_METHOD__ 0
#define __MMX__ 1
#define __SSE__ 1
#define __SSE2__ 1
#define __SSE_MATH__ 1
#define __SSE2_MATH__ 1
#define __SIZEOF_LONG__ 8
#define __SIZEOF_LONG_DOUBLE__ 16
#define __SIZEOF_SHORT__ 2
#define __SIZEOF_INT__ 4
#define __SIZEOF_LONG_LONG__ 8
#define __SIZEOF_FLOAT__ 4
#define __SIZEOF_DOUBLE__ 8
#define __SIZEOF_POINTER__ __SIZEOF_LONG__
#define __SIZEOF_SIZE_T__ __SIZEOF_LONG__
#define __SIZEOF_PTRDIFF_T__ __SIZEOF_LONG__
#define __SIZEOF_WCHAR_T__ __SIZEOF_INT__
#define __BUILTIN_H_CONSTEXPR__ inline
#define __ATOMIC_ACQ_REL 4
#define __ATOMIC_RELAXED 0
#define __builtin_unreachable()
#define __builtin_va_end(arg) ((void)0)
#define __const const
#define __inline inline
