#define __signed_chars__ 1	/* Predefined */
#define __PRAGMA_REDEFINE_EXTNAME 1	/* Predefined */
#define __DATE__ "Oct 26 2019"	/* Predefined */
#define __TIME__ "23:11:54"	/* Predefined */
#define __STDC__ 1	/* Predefined */
#define __STDC_VERSION__ 199409L	/* Predefined */
#define __STDC_HOSTED__ 1	/* Predefined */
#define __TI_C99_COMPLEX_ENABLED__ 1	/* Predefined */
#define __STDC_NO_THREADS__ 1	/* Predefined */
#define __edg_front_end__ 1	/* Predefined */
#define __EDG_VERSION__ 413	/* Predefined */
#define __EDG_SIZE_TYPE__ unsigned long	/* Predefined */
#define __EDG_PTRDIFF_TYPE__ long	/* Predefined */
#define __VERSION__ "EDG gcc 4.8 mode"	/* Predefined */
#define __CHAR16_TYPE__ unsigned short	/* Predefined */
#define __CHAR32_TYPE__ unsigned int	/* Predefined */
#define __TI_COMPILER_VERSION__ 1002000	/* Predefined */
#define __COMPILER_VERSION__ 1002000	/* Predefined */
#define __TI_COMPILER_VERSION_QUAL_ID__ 19254	/* Predefined */
#define __TI_COMPILER_VERSION_QUAL__ QUAL_LETTER	/* Predefined */
#define __C7000__ 1	/* Predefined */
#define __C7100__ 1	/* Predefined */
#define __SIZE_T_TYPE__ unsigned long	/* Predefined */
#define __PTRDIFF_T_TYPE__ long	/* Predefined */
#define __WCHAR_T_TYPE__ unsigned int	/* Predefined */
#define __TI_EABI__ 1	/* Predefined */
#define __ELF__ 1	/* Predefined */
#define __little_endian__ 1	/* Predefined */
#define __LITTLE_ENDIAN__ 1	/* Predefined */
#define __TI_STRICT_ANSI_MODE__ 0	/* Predefined */
#define __TI_WCHAR_T_BITS__ 32	/* Predefined */
#define __TI_GNU_ATTRIBUTE_SUPPORT__ 1	/* Predefined */
#define __TI_STRICT_FP_MODE__ 1	/* Predefined */
#define __CHAR_BIT__ 8	/* Predefined */
#define __SCHAR_MAX__ 127	/* Predefined */
#define __SHRT_MAX__ 32767	/* Predefined */
#define __INT_MAX__ 2147483647	/* Predefined */
#define __LONG_MAX__ 9223372036854775807	/* Predefined */
#define __LONG_LONG_MAX__ 9223372036854775807	/* Predefined */
#define __SIZEOF_INT__ 4	/* Predefined */
#define __SIZEOF_SHORT__ 2	/* Predefined */
#define __SIZEOF_LONG__ 8	/* Predefined */
#define __SIZEOF_LONG_LONG__ 8	/* Predefined */
#define __SIZEOF_WCHAR_T__ 4	/* Predefined */
#define __SIZEOF_FLOAT__ 4	/* Predefined */
#define __SIZEOF_DOUBLE__ 8	/* Predefined */
#define __SIZEOF_LONG_DOUBLE__ 8	/* Predefined */
#define __SIZEOF_SIZE_T__ 8	/* Predefined */
#define __SIZEOF_WINT_T__ 4	/* Predefined */
#define __SIZEOF_PTRDIFF_T__ 8	/* Predefined */
#define VCOP_SIMD_WIDTH 8
#define _INLINE 1
#define __sa_scale_char 1	/* Predefined */
#define __sa_scale_char2 1	/* Predefined */
#define __sa_scale_cchar 2	/* Predefined */
#define __sa_scale_char3 1	/* Predefined */
#define __sa_scale_char4 1	/* Predefined */
#define __sa_scale_cchar2 2	/* Predefined */
#define __sa_scale_char8 1	/* Predefined */
#define __sa_scale_cchar4 2	/* Predefined */
#define __sa_scale_char16 1	/* Predefined */
#define __sa_scale_cchar8 2	/* Predefined */
#define __sa_scale_char32 1	/* Predefined */
#define __sa_scale_cchar16 2	/* Predefined */
#define __sa_scale_char64 1	/* Predefined */
#define __sa_scale_cchar32 2	/* Predefined */
#define __sa_scale_uchar 1	/* Predefined */
#define __sa_scale_uchar2 1	/* Predefined */
#define __sa_scale_uchar3 1	/* Predefined */
#define __sa_scale_uchar4 1	/* Predefined */
#define __sa_scale_uchar8 1	/* Predefined */
#define __sa_scale_uchar16 1	/* Predefined */
#define __sa_scale_uchar32 1	/* Predefined */
#define __sa_scale_uchar64 1	/* Predefined */
#define __sa_scale_short 2	/* Predefined */
#define __sa_scale_short2 2	/* Predefined */
#define __sa_scale_cshort 4	/* Predefined */
#define __sa_scale_short3 2	/* Predefined */
#define __sa_scale_short4 2	/* Predefined */
#define __sa_scale_cshort2 4	/* Predefined */
#define __sa_scale_short8 2	/* Predefined */
#define __sa_scale_cshort4 4	/* Predefined */
#define __sa_scale_short16 2	/* Predefined */
#define __sa_scale_cshort8 4	/* Predefined */
#define __sa_scale_short32 2	/* Predefined */
#define __sa_scale_cshort16 4	/* Predefined */
#define __sa_scale_ushort 2	/* Predefined */
#define __sa_scale_ushort2 2	/* Predefined */
#define __sa_scale_ushort3 2	/* Predefined */
#define __sa_scale_ushort4 2	/* Predefined */
#define __sa_scale_ushort8 2	/* Predefined */
#define __sa_scale_ushort16 2	/* Predefined */
#define __sa_scale_ushort32 2	/* Predefined */
#define __sa_scale_int 4	/* Predefined */
#define __sa_scale_int2 4	/* Predefined */
#define __sa_scale_cint 8	/* Predefined */
#define __sa_scale_int3 4	/* Predefined */
#define __sa_scale_int4 4	/* Predefined */
#define __sa_scale_cint2 8	/* Predefined */
#define __sa_scale_int8 4	/* Predefined */
#define __sa_scale_cint4 8	/* Predefined */
#define __sa_scale_int16 4	/* Predefined */
#define __sa_scale_cint8 8	/* Predefined */
#define __sa_scale_uint 4	/* Predefined */
#define __sa_scale_uint2 4	/* Predefined */
#define __sa_scale_uint3 4	/* Predefined */
#define __sa_scale_uint4 4	/* Predefined */
#define __sa_scale_uint8 4	/* Predefined */
#define __sa_scale_uint16 4	/* Predefined */
#define __sa_scale_long 8	/* Predefined */
#define __sa_scale_long2 8	/* Predefined */
#define __sa_scale_clong 8	/* Predefined */
#define __sa_scale_long3 8	/* Predefined */
#define __sa_scale_long4 8	/* Predefined */
#define __sa_scale_clong2 8	/* Predefined */
#define __sa_scale_long8 8	/* Predefined */
#define __sa_scale_clong4 8	/* Predefined */
#define __sa_scale_ulong 8	/* Predefined */
#define __sa_scale_ulong2 8	/* Predefined */
#define __sa_scale_ulong3 8	/* Predefined */
#define __sa_scale_ulong4 8	/* Predefined */
#define __sa_scale_ulong8 8	/* Predefined */
#define __sa_scale_float 4	/* Predefined */
#define __sa_scale_float2 4	/* Predefined */
#define __sa_scale_cfloat 8	/* Predefined */
#define __sa_scale_float3 4	/* Predefined */
#define __sa_scale_float4 4	/* Predefined */
#define __sa_scale_cfloat2 8	/* Predefined */
#define __sa_scale_float8 4	/* Predefined */
#define __sa_scale_cfloat4 8	/* Predefined */
#define __sa_scale_float16 4	/* Predefined */
#define __sa_scale_cfloat8 8	/* Predefined */
#define __sa_scale_double 8	/* Predefined */
#define __sa_scale_double2 8	/* Predefined */
#define __sa_scale_cdouble 8	/* Predefined */
#define __sa_scale_double3 8	/* Predefined */
#define __sa_scale_double4 8	/* Predefined */
#define __sa_scale_cdouble2 8	/* Predefined */
#define __sa_scale_double8 8	/* Predefined */
#define __sa_scale_cdouble4 8	/* Predefined */
